### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found few misspellings.

https://github.com/crate-ci/typos

Do you want to discover more? (with Hunspell)

### CODE REVIEW

**Comment by szepeviktor** [comment]
@roberto-butti Here you go!

Hunspell + LibreOffice/dictionaries

**Comment by szepeviktor** [comment]
Do you use a language tool like DeepL Write?

**Comment by roberto-butti** [comment]
Wow! a lot of typos :)
The tool you suggested looks amazing. I will take a look.
Thank you @szepeviktor   for the suggestion and for the PR!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
